from typing import Optional, Union, Iterable

import torch
from torch import nn, inf


class GradScalerWithNormTracking:
    """
    Gradient scaler with norm tracking and gradient clipping support.

    Wraps PyTorch's GradScaler while adding:
    - Gradient norm computation
    - Gradient clipping
    - Optional gradient update control
    """

    state_dict_key = "amp_scaler"

    def __init__(self):
        self._scaler = torch.cuda.amp.GradScaler()

    def __call__(self,
                 parameters: Iterable[torch.Tensor],
                 loss: torch.Tensor,
                 optimizer: torch.optim.Optimizer,
                 max_grad_norm: Optional[float] = None,
                 create_graph: bool = False,
                 update_grad: bool = True) -> Optional[torch.Tensor]:

        """
        Execute scaled backward pass and optionally update weights.

        Args:
            parameters (Iterable[torch.Tensor]): Parameters to clip/check norms for
            loss (torch.Tensor): Loss tensor to backward from
            optimizer (torch.optim.Optimizer): Optimizer for the parameters
            max_grad_norm (float): If not None, clip gradients to this value
            create_graph (bool): Whether to create computation graph
            update_grad (bool): Whether to update weights (False for gradient only)

        Returns:
            torch.Tensor or None: Gradient norm if computed, else None
        """

        # Scale loss and perform backward pass
        self._scaler.scale(loss).backward(create_graph=create_graph)

        if not update_grad:
            return None

        # Unscale before clipping/norm computation
        self._scaler.unscale_(optimizer)

        if max_grad_norm is not None:
            grad_norm = nn.utils.clip_grad_norm_(parameters,
                                                 max_norm=max_grad_norm)
        else:
            grad_norm = self.get_gradient_norm(parameters)

        # Update weights and scaler state
        self._scaler.step(optimizer)
        self._scaler.update()

        return grad_norm

    @staticmethod
    def get_gradient_norm(parameters: Union[torch.Tensor, Iterable[torch.Tensor]],
                          norm_type: float = 2.0) -> torch.Tensor:
        """
        Compute gradient norm across parameters.

        Args:
            parameters (Iterable[torch.Tensor]): Model parameters or tensor to compute norm for
            norm_type (float): Type of norm to compute (2.0 for L2, inf for max norm)

        Returns:
            torch.Tensor: Total norm of gradients (scalar tensor)
        """

        if isinstance(parameters, torch.Tensor):
            parameters = [parameters]

        # Filter parameters with gradients
        parameters = [p for p in parameters if p.grad is not None]
        norm_type = float(norm_type)

        if not parameters:
            return torch.tensor(0.0)

        device = parameters[0].grad.device

        if norm_type == inf:
            # Max norm
            norms = (p.grad.detach().abs().max().to(device) for p in parameters)
            grad_norm = max(norms)
        else:
            # Lp norm
            norms = [torch.norm(p.grad.detach(), norm_type).to(device)
                     for p in parameters]
            grad_norm = torch.norm(torch.stack(norms), norm_type)

        return grad_norm

    def state_dict(self) -> dict:
        """
        Returns the state of the gradient scaler as a dictionary.

        Returns:
            dict: A dictionary containing all scaler state information. Compatible with
            PyTorch's native GradScaler state format.
        """

        return self._scaler.state_dict()

    def load_state_dict(self,
                        state_dict: dict) -> None:
        """
        Loads the gradient scaler state from a state dictionary.

        Args:
            state_dict (dict): Scaler state dictionary, typically generated by
            calling state_dict() on a compatible gradient scaler. Must contain
            all necessary keys for PyTorch's GradScaler.

        Raises:
            RuntimeError: If the state_dict is incompatible with the scaler's
            expected state format.
        """

        self._scaler.load_state_dict(state_dict)


def build_amp_scaler() -> GradScalerWithNormTracking:
    """
    Factory function that creates and returns a new gradient scaler with norm tracking.

    Returns:
        GradientScalerWithNormTracking: A new instance of the gradient scaler with
        default initialization parameters, ready for mixed-precision training.
    """

    return GradScalerWithNormTracking()
