event_vision_model:
  type: GET
  parameters:
    patch_size: 4
    embed_dim: 48
    depths: [2, 2, 8]
    num_heads: [3, 6, 12]
    window_size: 8
    mlp_ratio: 4.0
    drop_rate: 0.2
    attn_drop_rate: 0.0
    drop_path_rate: 0.2
    use_checkpoint: False
    embed_split: 12
    group_num: 12
  projection_dim: 128
  num_event_tokens: 64

data:
  data_path: "/data/storage/anastasia/data/CIFAR10DVS"
  sensor_size: [128, 128]
  ref_resolution: 128
  batch_size: 1024
  num_workers: 2
  augmentation:
    max_shift: 50
    hor_flip_p: 0.5
    time_flip_p: 0.8
    center_p: 0.5
    time_crop_p: 0.8
    time_drop_ratio: 0.1
    area_drop_ratio: 0.1
    point_drop_ratio: 0.1
    noise_std: 0.1
    verbose: False

train:
  optimizer:
    lr: 0.0002
    weight_decay: 0.05
  objective:
    name: ntxent
    temperature: 0.1
    eps: 1.0e-6
  scheduler:
    name: 'cosine_restarts'
    first_cycle_steps: 2000
    cycle_mult: 1.0
    warmup_steps: 1000
    gamma: 0.1
    last_epoch: -1
    max_lr: 3.2e-3
    min_lr: 2.0e-5
  max_grad_norm: 5.0
  num_epochs: 200
